export const QUERY_KEYS = {
  CREATE_TODO: "CREATE_TODO",
  CHANGE_CHECK_TODO: "CHANGE_CHECK_TODO",
  DELETE_TODO: "DELETE_TODO",
  EDIT_TODO: "EDIT_TODO",
  GET_TODOS: "GET_TODOS",
  GET_TODO_ATTACHMENT: "GET_TODO_ATTACHMENT",
  UPLOAD_TODO_ATTACHMENT: "UPLOAD_TODO_ATTACHMENT",
};
